---
# Import the repository signing key:
- name: import postgresql repository signing key
  apt_key:
    url: "{{ repo_signing_key }}"
    state: present

# Add the repository configuration file:
- name: 'add postgresql repository'
  apt_repository:
     repo: "{{ postgresql_repo }}"
     state: present

- name: installing required packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present