---
- name: add postgresql apt-key
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    state: present
  tags:
    - install

- name: 'add postgresql repository'
  apt_repository:
     repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
     state: present
  tags:
    - install

- name: installing required packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  tags:
    - install