---
# Variable configuration.
- name: Apply the db tag to the include and to all tasks in db.yaml
  include_tasks:
    file: variables.yml

# Include tasks
- name: Include tasks install-{{ ansible_distribution }}.yml
  include_tasks:
    file: install-{{ ansible_distribution }}.yml
  when: ansible_distribution == 'Ubuntu'
  tags: install