---
# Include variable based on the distribution.
- name: Include variable based on the distribution.
  ansible.builtin.include_vars: "vars/{{ ansible_distribution }}.yml"

# Include tasks
- name: Include tasks based on the distribution.
  include_tasks:
    file: "{{ ansible_distribution }}.yml"
