---

- name: Include Ubuntu variables.
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Define postgresql_version.
  set_fact:
    postgresql_version: "{{ __postgresql_version }}"
  when: postgresql_version is not defined

- name: Define postgresql_daemon.
  set_fact:
    postgresql_daemon: "{{ __postgresql_daemon }}"
  when: postgresql_daemon is not defined

- name: Define postgresql_repo.
  set_fact:
    postgresql_repo: "{{ __postgresql_repo }}"
  when: postgresql_repo is not defined

- name: Define repo_signing_key.
  set_fact:
    repo_signing_key: "{{ __repo_signing_key }}"
  when: repo_signing_key is not define

- name: Define postgresql_repo_enabled.
  set_fact:
    postgresql_repo_enabled: "{{ __postgresql_repo_enabled }}"
  when: postgresql_repo_enabled is not defined

- name: Define postgresql_packages.
  set_fact:
    postgresql_repo: "{{ __postgresql_packages }}"
  when: postgresql_packages is not defined