---
- name: start postgresql
  service:
    name: "{{ postgresql_daemon | default(__postgresql_daemon) }}"
    state: "{{ postgresql_restarted_state | default(__postgresql_restarted_state) }}"
    sleep: 5
